Cím: The Minecraft Story
Szereplők: 
-	Steve
-	Daisy (steve kutyája)
-	Alex
-	Notch
-	Herobrine
-	Edixare
Történet vázlata:
-	Notch a minecraft világ istene, a világ kezdetekor megteremti Stevet és Alexet
-	Steve és Alex a minecraft világban éltek és élték mindennapjaikat.
-	Steve és Alex között a kapcsolat egyre inkább szorosabbá válik!
-	A Mindennapjaik részét képezi a gazdálkodás, állatok tenyésztése, kereskedés a falusiakkal!
-	Egy nap Steve felfedezőútra megy hű kutyájával, Daisyvel, Alex otthon marad
-	Steve olyan területeket fedez fel, amit még nem ismer.
-	Steve egy ősi templomot talál
-	Steve bemegy a templomba és talál egy ősi kaput, ami a Netherbe vezet!
-	Steve átmegy a kapun, kutyája kint marad
-	Steve lát a kapu túloldalán egy hatalmas tükröződő falat.
-	Átmegy a kapun, hogy közelebbről is megvizsgálja!
-	A tükör képe azonban furcsa módon eltorzul!
-	A tükör képén a szemei fehérré változnak, és a tükör képe önállósul, és a tükrön keresztül megüti Stevet, és visszaüti a porálba, ahol visszakerül a felszíni világban.
-	A kutyája látja Steven, hogy nem mozdul.
-	Daisy visszasiet Alexhez
-	Az idő esteledik.
-	 Alex hazaviszi Stevet.
-	Steve rosszul érzi magát, és egész éjjel öntudatlan állapotban van.
-	Stevet rossz álmok bántják.
-	Az álmaiban töredékesen egy ősi háborút lát, ami réged dúlt!
-	Reggel, amikor felébred, látszólagosan jobban érzi magát.
-	Alex örül neki, hogy Steve jobban érzi magát.
-	Alex kérdezni kezdte őt, hogy mi történt?
-	Steve elmesélte, hogy egy kapunk keresztül látott valamit.
-	Alex nem érti, ugyanis amikor rátalált, nem volt semmilyen kapu a közelében.
-	Steve sem érti, inkább hanyagolják a témát!
-	Ezek után, elmennek halászni!
-	Halászat közben Steve, miközben a vizet bámulta, látomást látott!
-	Látomása egy titokzatos alakról szólt, aki ugyan úgy nézett ki, mint ő, csak a szemei fehérek voltak. 
-	Alex szólítja Stevet, de nem válaszol neki! 
-	Többszöri szólítás után Steve visszatér a látomásból, és úgy csinál, mint akinek semmi baja
-	Alex aggódik Steve miatt, ezért felkeresi a házuktól nem messzire található falu varázslóját.
-	A varázsló, akinek a neve Edixare fogadja Alexet hatalmas könyvtárában!
-	Alex elmeséli, amit Steve mondott neki.
-	A varázslót elönti a félelem. Tudta, hogy mit jelent.
-	Alex kérte, hogy mondja el neki is, hogy mi történik Stevevel.
-	Elmesélte neki, hogy réges-régen, az idők kezdetekor, amikor még nem voltak emberek, csak szörnyek a világon, volt egy nagy háború! A háború a 2 világ között zajlott.  Az istenek háborúja hatalmas volt! A világok közötti átjárókat, a portálokat Notch megsemmisítette, így a 2 világ között megszakadt a kapcsolat! A Nether istene, Herobrine volt. Ő volt Notch első teremtménye. Herobrine elárulta Notchot és isten szeretett volna lenni! Herobrine hatalmas erőkre tett szert, a tiltott tanokat kezdte el tanulni. Notchnak ez nem tetszett, ezért száműzte Herobrinet a Netherbe(pokolba). Herobineról azóta sem tudunk semmit! Notch ezután teremtette meg Stevet és Alexet!
-	Alex, miután elmesélte neki ezt Edixare, megkérdezte, hogy mi történik Stevevel.
-	Edixare szerint, valószínűleg Herobrine meg kísértette, hogy visszatérhessen a felszínre, és legyőzze Notchot és átvegye a hatalmat!
-	Alex kérdezte Edixaret, hogy van e valami megoldás!
-	Edixare szerint, amennyiben Herobrine visszatér, Steve örökre meghal.
-	Alex sírva visszament a házukba, Stevehez.
-	Steve nem értette, hogy miért aggódik érte Alex.
-	Alex nem adja fel, és megpróbál megoldást találni.
-	Alex és Steve házához másnap reggel kereskedő falusiak érkeztek
-	A kereskedők a világ számtalan helyein jártak és kereskednek mindenfélékkel.
-	A kereskedők ajánlanak egy vaskardot nekik.
-	Steve meglátja a vaskardot, és megint látomása lesz.
-	A látomásban Herobrine látható, ahogyan a vaskardal megöli őt.
-	Steve a látomása után azonnal elküldte őket!
-	 Alex ezután elment a varázsló fő könyvtárába kutatni!
-	Ez idő alatt Stevenek egy újabb látomása lesz.
-	Ez a látomás más, ugyanis tud benne közlekedni.
-	A látomásában egy hatalmas kastélyban találta magát
-	A kastélyban látta a vaskardot, amit a korábbi vízióiban is látott.
-	Ezután tovább ment a kastélyban.
-	Hirtelen találkozik Herobrine-al!
-	Herobrine súg neki valamit, és Steve azonnal visszatér a látomásból. 
-	Alex ez idő alatt talált egy ősi könyvet. A könyv elmondja, hogyan lehet kapcsolatba lépni Notchal.
-	A könyv szerint egy ősi fát kell felkutatniuk, amely tetején található egy kút! A kút vizéből inniuk kell, és ezt követően találkoznak Notchal!
-	Alex azonnal útnak indul Stevevel együtt, hogy segítséget kérjenek Notchtól!
-	A könyvben talált Alex es térképet.
-	Alex és Steve elindulnak a térképet követve az ősi fa felkutatásához!
-	Az út során több bonyodalomba keverednek.
-	Egyszer egy hatalmas folyón való átkeléshez szükségük lesz egy hajóra.
-	Azonnal nekilátnak egy hajó készítéséhez. 
-	Azonban esteledik.
-	Tábort vernek, hogy másnak folytassák az építést.
-	Másnap, amikor elkészült az építés, felülnek a hajóra, és úgy mennek tovább.
-	A hajó azonban hirtelen egy hatalmas örvénybe keveredik.
-	A hajót berántja az örvény, és beszippantja őket a tenger!
-	Alex és Steve öntudatlan állapotba keverednek!
-	Amikor felébrednek, egy hatalmas tengeri templomban találják magukat! A templomot azonban egy Őrző védi.
-	Az őrző szerint megsértették a templomot és be akartak törni.
-	Alex és Steve elmondták, hogy nem akartak ilyesmit, csak tovább szeretnének haladni.
-	Az Őrző csak akkor engedi el őket, amennyiben válaszolnak pár kérdésre.
-	Az őrző feltesz 3 kérdést.
-	Mind a 3-ra sikeresen tudják a válasz, és tovább engedi őket az Őrző.
-	Visszakapták a hajójukat és tovább mentek.
-	Éjszaka lett és aludni kezdtek.
-	Stevet tovább kísértik az álmok!
-	Másnap, arra ébrednek, hogy a hajó hánykolódik!
-	Felébredtek, és észrevették, hogy egy hatalmas vízesés felé haladnak!
-	Próbáltak visszafordulni, de nem sikerült. Leestek a vízesésen a hajójukkal!
-	A hajó összetört és nem tudtak tovább haladni.
-	A vízesés alján, körbevették őket egy bennszülöttekből álló csoport!
-	A csoport elvitte őket a falujukba. 
-	Amint haladtak a falu felé, észrevettek egy hatalmas fát!
-	Kiderült, hogy ide készültek jönni!
-	A falu vezetőjével találkoztak. A falu vezetője segített nekik.
-	Kaptak élelmet, ruházatot.
-	Steve és Alex elmondta, hogy a nagy fához szeretnének menni.
-	A falu lakóit ezt hallatán félelem töltötte el!
-	A falu sámánja szerint a fát ősi átok kísérti. Többen mentek fel a fára, de még soha senki sem jött vissza!
-	Alex aggódott Steve miatt, és ennek ellenére megindult a fára mászni!
-	A fára, ahogy mászott és mászott fel, több misztikus szörny próbálta megölni Alexet.
-	Alex, miután legyőzte a szörnyeket, megtalálta a kutat. Ívott belőle és álomba zuhant.
-	Ez idő alatt Steveet, amig lent várt a fa előtt Alexet, újra vízió gyötri. A falu sámánja ezt látta, és azt kiáltotta: „DÉMOM!” 
-	A falu egyik katonája megakarta ölni Stevet, de amint megérintette Stevet, egy hatalmas vörös kisugárzó erő letarolt mindent Steve körül!
-	Alex, miután elaludt, álmában találkozott Notchal!
-	Elmondta, hogy Stevet Herobrine kísérti!
-	Notch csak ennyit mondott: „Mit tettél?”
-	Ez idő alatt kint a robbanást követően minden lángba borult.
-	A fa égett a tűztől.
-	Notch elmondta, hogy csak egyetlen egy megoldás létezik, ha megölik Stevet!
-	Alex ezt hallatán nagyon dühös lett.
-	Alex visszatért az álmából
-	Alex körül minden égett, lángokba borult. Hatalmas volt a füst.
-	Alex próbált felállni, de nem tudott. 
-	Alex meglátta Stevet, ahogy feljött a fára, és oda ment a kúthoz.
-	Alex kérte Stevet, hogy segítsen.
-	Azonban Steve, mikor ránézett Alexre, szemei fehéren világítottak.
-	Túl késő volt.
-	Stevet megszállta Herobrine!
-	Herobrine megköszönte, hogy elhozta a kúthoz! A kút egy egyetlen kapcsolat a világ és az istene között! A kút vizének segítségével Herobrine találkozni tudod Notchal, hogy aztán végezzen vele!
-	Herobrine ívott a vízből, és eltűnt!
-	Alex ezt végig nézte, és elájult!
-	Másnap reggel, mindent a hamu borított! A bennszülöttek megtalálták Alexet. 
-	Alex haldoklott.
-	A falu sámánja azonban készített egy mágikus főzetet.
-	A főzet varázserővel bírt. 
-	A főzet felruházta erővel azt, aki megissza.
-	A főzet segítségével Alex meg gyógyult, és sokkal erősebb lett!
-	Ez idő alatt Notch és Herobrine között elkezdődött a harc!
-	Alex elhatározta, hogy megkeresi Herobrinet, és megpróbálja Stevet megmenteni!
-	Alex elkezdte kiképezni magát. 
-	Megtanult kardot forgatni és harcolni!
-	A sámán elkezdi a kiképzését, és a falu tagjává avatják!
-	Alex részt vesz a szertartáson, amivel hivatalosan is a bennszülött falu tagjává válik!
-	Alex ezt követően elindul felkutatni Herobrinet, hogy megmentse Steve-t!
-	Ezután Herobrine és Notch között a harc véget ért!
-	A harcban Herobrine elmenekült vissza a Netherbe!
-	Herobrine tudta, hogy nem győzheti le Notchot!
-	Herobrine csak el akarta lopni Notch nagy könyvét, amivel Notch teremtette a világot!
-	Notch nem veszi észre, hogy hiányzik a könyv!
-	Herobrine, miután visszatért a Netherbe, saját katonákat és szörnyeket teremt, amivel lerohanhatja a világot! 
-	Alex visszamegy a házukhoz!
-	Daisy kutyus azóta is várta Steve-t és Alex-t hogy visszatérjenek!
-	Alex hazatér és a kutya üdvözli őt!
-	Alex kiönti szívét a kutyusnak!
-	Alex felkeresi Edixare-t!
-	Alex segítséget kér tőle a Netherbe való jutáshoz!
-	Edixare a könyvekben kutat a megoldásért!
-	Edixare és Alex hosszas kutatást követően megtalálja a megoldást!
-	A megoldás az, ha felkutatjuk az ősi istenek háborújakor épült Nether kaput, ami a föld alatt húzódik valahol egy barlangban! 
-	Edixare elmondja, melyik királyságban található a kapu, de nem tudja pontosan, hogy hol!
-	Alex elindul a királyságba!
-	Alex Daisy kutyával együtt elindulnak a másik királyságba!
-	Útjuk során, amikor már esteledik, egy faluhoz érnek! 
-	Herobrine, miközben a könyvel teremt, furcsán viselkedik.
-	Herobrine érzelem jeleit mutatja.
-	Valahol legbelül még Steve él Herobrine-ban!
-	Herobrine a könyv segítségével még erősebb lett! 
-	Herobrine terve az, hogy legyőzi Notch-t és átveszi a hatalmat!
-	Alex a másik királyságukba vezető úton egy faluban megalszanak, mert este lett.
-	Alex itt ismerkedik egy kicsit a falusiakkal.
-	Alex másnap reggel, miután kapott élelmet és vizet, elindul tovább a másik birodalomba!
-	Alexet az út során számos kaland éri.
-	Alex a kalandok során ismerkedik új erejével és képességeivel!
-	Alex eléri a másik birodalmat!
-	Alex felkeresi a bányászokat, ugyanis ők ismerik a legjobban a barlangokat
-	A bányászok szerint nem tudják, hogy hol van a kapu.
-	Alex felkeresi a birodalom varázslóját.
-	A varázsló elmondja neki, hogy hol található a barlang, ahol a kapu van! 
-	Alex felkutatja a kaput, majd a varázsló segítségével aktiválja a kaput!
-	A kapu segítségével átmegy a Nether-be Alex!
-	Alex egy kietlen, pokoli helyen találja magát.
-	Elindul a Nether-ben, hogy felkutassa Herobrinet!
-	Herobrine eközben a könyv segítségével épített egy kaput, ami eljuttatja őt és hadseregét és szörnyeit Notch-hoz!
-	Herobrine aktiválja a kaput, és seregével lerohanja Notch-ot!
-	Eközben Alex megismeri a Nether másik oldalát is!
-	Talál egy Nether falut
-	A faluban gyerekek, férfiak, nők, állatok találhatóak!
-	Alex hirtelen megdöbbent, hogy létezik jó is a Nether-ben! 
-	A fenti világban a tanítások szerint a Nether-ben csak a gonoszság és szörnyek vannak!
-	Alex segítséget kap a faluban!
-	Alex ezután megtudja, hogy Herobrine hol épített kaput!
-	Alex elindul felkutatni a kaput a Nether-ben!
-	Alex megtalálja a kaput.
-	Számos harcba keveredik, de Alex legyőzi azokat, akik az utába állnak!
-	Alex megtalálja a kaput és átmegy rajta!
-	Alex éppen akkor érkezik meg, amikor Notch és Herobrine küzdenek egymással!
-	Notch éppen meg akarta ölni Herobrine-t
-	Alex azonban nem engedte meg Notch-nak!
-	Alex azonban megpróbálja visszahozni Stevet!
-	Alex szimpátiát mutat és próbál olyanokat mondani Herobrine-nak, ami előcsalhatja belőle Stevet!
-	 Herobrine furcsán kezd viselkedni, és úgy tűnik, hogy steve ott van még valahol!
-	Herobrine és Steve lelke őrül harcot vív.
-	Azonban Alexnek hála Herobrine fehéren izzó szemei lassan visszaváltoznak normálisra!
-	Alexnek látszólag sikerül visszahoznia Stevet!
-	Notch látta, hogy kettejük között milyen a kötelék.
-	Notch visszaküldte őket a házukba, hogy tovább éljék mindennapjaikat!
-	Azonban, amikor Alex és Steve hazatér, váratlan dolog történik!
-	Éjszaka, Steve kimegy a házuk előtt található tóhoz.
-	Alex Steve után megy.
-	Alex leül Steve mellé, és a vállára teszi a fejét.
-	Steve, miközben nézi a vizet, egy szempillantás erejéig az egyik szeme visszaváltozik fehérré! 


